### PR TITLE
Fix #167

### LINKED ISSUE #167: Fails to correctly parse key with escaped forward slash
When attempting to parse the following string:

```
{"a\/b":"c\"d\"e","f":1}
```

The following value is created:

```
{
  "a/b": null,
  "c\"d": "c\"d\"e",
  "f": 1
}
```

It seems the combination of the escaped forward slash and the escaped quote in the value causes the parser to fail to attach the value in the correct location.

### PR DESCRIPTION
**Pull request by aembke**
Fixes https://github.com/maciejhirsz/json-rust/issues/167 and prevents panics found in the `stringify` function when fuzzing with AFL. 

Also adds a number of tests to reproduce the fuzzing results and to test the changes to the parsing logic.

### CODE REVIEW

File: src/codegen.rs [hunk 1]
```diff
@@ -66,20 +66,20 @@ pub trait Generator {
 
     #[inline(never)]
     fn write_string_complex(&mut self, string: &str, mut start: usize) -> io::Result<()> {
-        self.write(string[ .. start].as_bytes())?;
+        self.write(&string.as_bytes()[ .. start])?;
```
Comment (alecembke-okta) [inline src/codegen.rs]: the changes in this function prevent panics when indexing into a string at a byte offset that doesn't fall on a character boundary

**Comment by maciejhirsz** [comment]
Thank you!
