### PR TITLE
Resolves #125 - Accept trailing commas in object!{}

### LINKED ISSUE #125: Could we teach object! to accept trailing commas
Right now,

```rust
object!{
  "foo" => "bar",
}
```

fails because of the trailing comma. It would be nicer to accept them, as in the rest of Rust.

### PR DESCRIPTION
**Pull request by Yoric**

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -308,8 +308,12 @@ macro_rules! array {
 /// ```
 #[macro_export]
 macro_rules! object {
+    // Empty object.
     {} => ($crate::JsonValue::new_object());
 
+    // Non-empty object, no trailing comma.
+    //
+    // In this implementation, key/value pairs separated by commas.
     { $( $key:expr => $value:expr ),* } => ({
```
Comment (maciejhirsz) [inline src/lib.rs]: To keep things DRY, we could change this version of the macro to have body of:

```rs
object!($( $key => $value, )*)
```

Comment (maciejhirsz) [reply src/lib.rs]: Actually I can just do that quickly, thanks! :)
